import "./globals.css";
import ClientLayout from "./components/wrapping/ClientLayout";
import LenisProvider from "./components/LenisProvider";

export const metadata = {
  title: "Bootcamp",
  description: "Generated by CodeXabhi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className="antialiased">
      {/* <ClientLayout> */}
        {/* <LenisProvider> */}
        {children}
        
        {/* </LenisProvider> */}
      
      {/* </ClientLayout> */}
     
    </body>
    </html >
  );
}
